[package]
name = "fizzy"
version = "3.0.0"
build = "build.rs"
readme = "README.md"
license = "Apache-2.0"
keywords = ["configuration management", "tool", "commandline"]
authors = ["Alessandro Molari <molari.alessandro@gmail.com>"]
description = "The hassle-free configuration manager"
homepage = "https://alem0lars.github.io/fizzy"
repository = "https://github.com/alem0lars/fizzy"
documentation = "https://alem0lars.github.io/fizzy"

[lib]
name = "fizzy"

[[bin]]
name = "fizzy"
doc = false

[dependencies]
clap = "~2"
log = "~0.3"
env_logger = "~0.3"
chrono = "~0.3"
serde = "~0.9"
serde_derive = "~0.9"
envy = "~0.2"

[dev-dependencies]
skeptic = "~0.5"

[build-dependencies]
skeptic = "~0.5"
clog = "~0.9"
clap = "~2"
